INSERT INTO skills (skills_name) VALUES (".NET Framework");
INSERT INTO skills (skills_name) VALUES ("Agile");
INSERT INTO skills (skills_name) VALUES ("AJAX");
INSERT INTO skills (skills_name) VALUES ("Angular 4+");
INSERT INTO skills (skills_name) VALUES ("APIs");
INSERT INTO skills (skills_name) VALUES ("ASP.NET");
INSERT INTO skills (skills_name) VALUES ("Big data");
INSERT INTO skills (skills_name) VALUES ("Bootstrap");
INSERT INTO skills (skills_name) VALUES ("C");
INSERT INTO skills (skills_name) VALUES ("C#");
INSERT INTO skills (skills_name) VALUES ("C++");
INSERT INTO skills (skills_name) VALUES ("Cake3");
INSERT INTO skills (skills_name) VALUES ("Chrome");
INSERT INTO skills (skills_name) VALUES ("CI/CD");
INSERT INTO skills (skills_name) VALUES ("CSS");
INSERT INTO skills (skills_name) VALUES ("Cucumber");
INSERT INTO skills (skills_name) VALUES ("Docker");
INSERT INTO skills (skills_name) VALUES ("Eclipse");
INSERT INTO skills (skills_name) VALUES ("Edge");
INSERT INTO skills (skills_name) VALUES ("Firefox");
INSERT INTO skills (skills_name) VALUES ("Functional programming");
INSERT INTO skills (skills_name) VALUES ("Git");
INSERT INTO skills (skills_name) VALUES ("GitHub");
INSERT INTO skills (skills_name) VALUES ("HTML5");
INSERT INTO skills (skills_name) VALUES ("IntelliJ");
INSERT INTO skills (skills_name) VALUES ("Internet Explorer");
INSERT INTO skills (skills_name) VALUES ("Java");
INSERT INTO skills (skills_name) VALUES ("Javascript");
INSERT INTO skills (skills_name) VALUES ("Jenkins");
INSERT INTO skills (skills_name) VALUES ("Jira");
INSERT INTO skills (skills_name) VALUES ("jQuery");
INSERT INTO skills (skills_name) VALUES ("JSON");
INSERT INTO skills (skills_name) VALUES ("LAMP");
INSERT INTO skills (skills_name) VALUES ("Linux");
INSERT INTO skills (skills_name) VALUES ("Machine learning");
INSERT INTO skills (skills_name) VALUES ("Mariadb");
INSERT INTO skills (skills_name) VALUES ("MEAN");
INSERT INTO skills (skills_name) VALUES ("Microservices");
INSERT INTO skills (skills_name) VALUES ("Microsoft SQL Server");
INSERT INTO skills (skills_name) VALUES ("MongoDB");
INSERT INTO skills (skills_name) VALUES ("monorepo");
INSERT INTO skills (skills_name) VALUES ("MVC");
INSERT INTO skills (skills_name) VALUES ("MySQL");
INSERT INTO skills (skills_name) VALUES ("nltk");
INSERT INTO skills (skills_name) VALUES ("nodejs");
INSERT INTO skills (skills_name) VALUES ("nx");
INSERT INTO skills (skills_name) VALUES ("nxdev");
INSERT INTO skills (skills_name) VALUES ("Object-Oriented design");
INSERT INTO skills (skills_name) VALUES ("Pandas");
INSERT INTO skills (skills_name) VALUES ("PHP");
INSERT INTO skills (skills_name) VALUES ("Postman");
INSERT INTO skills (skills_name) VALUES ("Protractor");
INSERT INTO skills (skills_name) VALUES ("Python2.7+");
INSERT INTO skills (skills_name) VALUES ("Python3+");
INSERT INTO skills (skills_name) VALUES ("Rapid Prototyping");
INSERT INTO skills (skills_name) VALUES ("REST");
INSERT INTO skills (skills_name) VALUES ("scikit");
INSERT INTO skills (skills_name) VALUES ("Service Oriented Architecture");
INSERT INTO skills (skills_name) VALUES ("sklearn");
INSERT INTO skills (skills_name) VALUES ("SOAP");
INSERT INTO skills (skills_name) VALUES ("Software Development");
INSERT INTO skills (skills_name) VALUES ("SQL");
INSERT INTO skills (skills_name) VALUES ("SQLite");
INSERT INTO skills (skills_name) VALUES ("Technical Writing");
INSERT INTO skills (skills_name) VALUES ("Typescript");
INSERT INTO skills (skills_name) VALUES ("Ubuntu");
INSERT INTO skills (skills_name) VALUES ("Unit Testing");
INSERT INTO skills (skills_name) VALUES ("User Interface (UI)");
INSERT INTO skills (skills_name) VALUES ("Visual Studio");
INSERT INTO skills (skills_name) VALUES ("vscode");
INSERT INTO skills (skills_name) VALUES ("Waterfall");
INSERT INTO skills (skills_name) VALUES ("Web Services");
INSERT INTO skills (skills_name) VALUES ("Written Communication");
INSERT INTO skills (skills_name) VALUES ("XML");